Fix fatal error after contact merge
colemanw/webform_civicrm pull request #210
Opened 2019-04-23 10:47 UTC by jitendrapurohit

Overview
----------------------------------------
Fix fatal error after contact merge - https://www.drupal.org/project/webform_civicrm/issues/3044643

Before
----------------------------------------
Fatal Error after performing contact merge in civicrm

After
----------------------------------------
Works fine.

Technical Details
----------------------------------------
Webform civi code tries to update the old contact id in submitted data to new value. It made use of `webform_component`  table which is not present in the updated drupal webform. 

This PR indents to do the same using the updated code format.

2019-04-30 13:51 UTC, jackrabbithanna commented
I'm sure that this code does what it says it will do. I am a little hesitant to recommend this course of action. In this particular case, a direct query may be better IMO because it is much more efficient. The problem with this solution is scaling. What happens if you have 100 webforms or 1 million submissions. That may seem a little extreme, and maybe it is, but even with 1 webform and 100K contacts, the submissions can add up real quick. Merging contacts can already get to be sort of intensive, and now add on top of that this sifting through all webforms and all submissions. There can be arguments against a direct query of course, updating the submission in that way will not invoke any hooks or trigger any events. Perhaps a webform could have a setting where the admins get to choose if the submissions are even updated or not, maybe it defaults to "do". Maybe even the method of updating could be chooseable...but that seems like some complex stuff to try to explain with good UI/UX. Regardless to what the stakeholders decide to do, it's not bad to have these types of internal discussions and think about scaling, and choice.

2019-04-30 15:14 UTC, jitendrapurohit commented
Agree with the above thought @jackrabbithanna I've recently started using d8 with webform and looks like both the table that were used before are removed from webform now.

I think the table that we need to update is `webform_submission_data` where `value` column matches the old contact id and `name` column should end with `_contact_existing` string. Sounds a little hackish but I think it should not affect any other scenarios. Previous comparison of "type = civicrm_contact" is not possible  I guess.

2019-04-30 17:42 UTC, jackrabbithanna commented
The type = civicrm_contact condition was against the webform_components table in the query for D7 version. I'm just starting to get involved with the D8 version of this project so I have some catching up and research to do.

2019-05-08 03:13 UTC, mglaman requested changes

2019-05-08 03:13 UTC, mglaman commented on webform_civicrm.module
> +      foreach ($elements as $key => $value) {
See `wf_crm_admin_form::handleDynamicCustomField`.

```
    /** @var \Drupal\webform\WebformInterface[] $webforms */
    $webforms = \Drupal\webform\Entity\Webform::loadMultiple();
    foreach ($webforms as $webform) {
      $handler_collection = $webform->getHandlers('webform_civicrm');

      if (!$handler_collection->has('webform_civicrm')) {
        continue;
      }
```

2019-05-08 03:13 UTC, mglaman commented on webform_civicrm.module
> +          $query = \Drupal::entityQuery('webform_submission')
Entity query is deprecated for retrieving the query directly from the entity storage.

2019-08-01 18:57 UTC, petednz commented
@jitendrapurohit is this something you need to be reviewing?

2020-04-28 16:14 UTC, KarinG commented
Closing this as I think this issue has been resolved with: https://github.com/colemanw/webform_civicrm/pull/283

2020-04-28 16:15 UTC, closed without merging