Fix soft credit contribution does not get created
colemanw/webform_civicrm pull request #68
Opened 2017-04-04 17:58 UTC by chanunc

This is a fix of soft credit contribution does not get created when making payment through webform which configured with Contribution page and “Soft Credit To”.

2017-04-04 19:07 UTC, colemanw commented
By design, you should create the soft credits within the webform and not on the contribution page. Maybe we could document this better.

Unless we get some votes in favor of this feature I think we probably should not add it.

2017-04-05 09:45 UTC, guanhuan commented
@chanunc can you add in complete issue description for this please.

Hi @colemanw, 

I don't think this a new feature (correct me if I am wrong). Currently the "Soft Credit To" field doesn't do anything when line item other than the contribution amount is involved and this is for fixing this issue.

2017-04-11 18:29 UTC, colemanw commented
@chanunc maybe I'm just not clear about what problem this is trying to solve. Can you please post steps to reproduce the bug?

2017-05-10 17:06 UTC, colemanw commented
Happy to reopen this if it gets clarified.

2017-05-18 18:29 UTC, chanunc commented
Hi Coleman, 
The business logic here is to create a webform for a buyer to purchase a membership for a recipient.

To reproduce 
### 1 .Set up Contribution page for membership payment
- Financial Type: Member Dues
- Set up dummy processor
- Enable Membership section
- Select a membership type (any)

### 2. Setup Webform and enable CiviCRM processing
- Add 2 individuals, one for buyer, one for recipent -> Save settings
- Select 0 Number of Memberships for buyer and select 1 to Number of Memberships for recipient -> Save settings
- Set up Contribution page to the one on the 1st step
- Set Soft Credit To: recipient -< Save settings

### 3. Proceed the webform to purchase membership for a recipient.
- Fill buyer and recipient form
- Purchase membership with test payment
- After complete the form, open the recipient contact page to check membership and contribution.

**Expected result:** 
The recipient contact should have a membership and contribution with soft credit from buyer contact.

**Faulty result:**
The recipient contact has a membership but not contribution with soft credit.

What I have found is Webform sent empty amount when it call CiviCRM API to create soft credit, therefore I have added a logic to get the amount firstly from contribution object, if the amount is empty then get the amount from line item calculation. 
More over, I also add default soft create type as a parameter when Webform call CiviCRM API to create soft credit.

2017-05-19 10:21 UTC, guanhuan commented
@colemanw please reopen. Please let @chanunc know if it all make sense to you and feedback if any. Thanks

2017-05-29 05:01 UTC, ghost requested changes
Shouldn't conditionally use the total amount, as this might be filled with a portion of the total

2017-05-29 05:01 UTC, agileware commented on includes/wf_crm_webform_postprocess.inc
> +      $amount = $contribution['total_amount'] != null ? $contribution['total_amount'] : $this->totalContribution;
This does not yield correct results if there is *also* a contribution amount field - and under some circumstances, e.g. a 5¢ additional contribution, reverts to the behaviour where the soft credit is not recorded.
I think better to just use `$this->totalContribution` regardless?

2017-05-29 23:50 UTC, agileware commented
Added an issue [https://www.drupal.org/node/2882281](#2882281) to the queue on drupal.org

2017-07-17 09:33 UTC, chanunc commented
@agileware Agree!
I have changed following your suggestion and tested with new installation of Drupal, Webform and CiviCRM.

2017-07-26 14:59 UTC, guanhuan commented
@colemanw can you take a look at this please? thank you

2017-07-29 18:28 UTC, colemanw commented on includes/wf_crm_webform_postprocess.inc
> +        'sequential' => 1,
`sequential` doesn't make sense as a param for api.getsingle.

2017-11-08 11:42 UTC, nishant-bhorodia commented
Hello @colemanw , 
Hope you are well!
Thanks for checking it out. I have updated the PR and removed sequential. 
Many Thanks :)

2017-11-08 17:22 UTC, KarinG commented
Before: on 4.6 is that the Soft Credit does get created - but that the amount is incorrect:
![image](https://user-images.githubusercontent.com/5340555/32563476-9c4fb9e8-c46e-11e7-89e0-9c690418426f.png)

2017-11-08 17:23 UTC, KarinG commented
Type is indeed empty: 
![image](https://user-images.githubusercontent.com/5340555/32563571-d72abefa-c46e-11e7-8ef3-6f41317f3ccb.png)

2017-11-08 17:25 UTC, KarinG commented
@chanunc - please note that you do not need to set up (on Contribution Page): "Enable Membership section" "Select a membership type (any)"

2017-11-08 17:30 UTC, KarinG commented on includes/wf_crm_webform_postprocess.inc
> +
Default ("Solicited" unless configured by admins) is ok for now - though there are 11 options in CiviCRM native - key purpose of this PR is to fix the $0.00 amount;

2017-11-08 17:37 UTC, KarinG commented
To summarize: 

- I've reproduced the issue on 4.6
- I've confirmed it's fixed on 4.6 (with this PR)

![image](https://user-images.githubusercontent.com/5340555/32564195-b2c053ca-c470-11e7-8f6b-d9addd540000.png)

If you can show us some screenshots that this is working on 4.7 - then this can be merged in.

2017-11-09 18:45 UTC, colemanw commented
Ok sounds like this is a net benefit. Merging.

2017-11-09 18:45 UTC, merged

2017-11-10 06:20 UTC, nishant-bhorodia commented
Thanks @colemanw @KarinG :)