set Tax rate to 2 decimal number
colemanw/webform_civicrm pull request #70
Opened 2017-04-11 17:11 UTC by vincent1892

VAT appear as 20.0000000000% no matter how many times you save it in civicrm "/civicrm/admin/financial/financialAccount?reset=1", this shows up on webforms as well. Fixed by changing the number format for $tax_rate.

2017-04-13 10:51 UTC, meladawy requested changes

2017-04-13 10:51 UTC, meladawy commented on includes/wf_crm_webform_preprocess.inc
> +          $tax_rate = number_format($this->tax_rate, 2); //strip trailing zeros from tax_rate e.g 20.00000% => 20.00%
Please add the comment in a separate line following instructions in https://www.drupal.org/node/1354

2017-04-13 14:19 UTC, vincent1892 commented
@meladawy  I've changed the comment style

2017-04-21 09:57 UTC, vincent1892 commented
@colemanw sorry to bother but could you please review this PR, we have a couple of tickets that are blocked cause of this?

2017-05-05 10:02 UTC, jamienovick commented
@vincent1892 this **shouldn't** be fixed to a number of d.p. -> It shouldn't show any '0' after the decimal place. i.e. If its 20.00000% it should show 20%; if its 20.125000% then 20.125% that should be shown.

2017-05-10 17:05 UTC, colemanw commented
@vincent1892 can you please check Jamie's comment?

2017-05-11 11:34 UTC, vincent1892 commented
@jamienovick @colemanw I've updated the PR. Webform now displays VAT without the trailing zeros.

2017-05-11 19:05 UTC, merged