Add new field to create relationship in additional options section
colemanw/webform_civicrm pull request #74
Opened 2017-06-13 05:42 UTC by jitendrapurohit

Fix for https://www.drupal.org/node/2511208

2017-06-13 15:21 UTC, colemanw requested changes

2017-06-13 15:21 UTC, colemanw commented on includes/wf_crm_webform_base.inc
> +    if ($this->settings['create_new_relationship']) {
I think you should wrap this variable in `!empty()` to avoid a possible php notice if it's not defined.

2017-06-14 10:55 UTC, jitendrapurohit commented on includes/wf_crm_webform_base.inc
> +    if ($this->settings['create_new_relationship']) {
Updated :-)

2017-06-14 14:23 UTC, colemanw requested changes

2017-06-14 14:23 UTC, colemanw commented on includes/wf_crm_webform_postprocess.inc
> +      if (empty($existing) !array_key_exists('start_date', $params) {
I'm having trouble reading this if statement. There's no operator between the two conditions.
Also it looks like there's a missing closing bracket. Did you try running this code? Looks like you'd get a fatal syntax error.

2017-06-14 14:53 UTC, jitendrapurohit commented on includes/wf_crm_webform_postprocess.inc
> +      if (empty($existing) !array_key_exists('start_date', $params) {
seems like it got messed up while pushing, was working fine while testing. I've tested the flow again and confirmed that it creates a new relationship when an expired/inactive duplicate relationship exists for a contact.

Thanks for spotting!

2017-06-14 14:57 UTC, merged